version: "3.3"
services:
    memcached:
      image: memcached:alpine
      networks:
        - proxy

    php-fpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      image: tribe-phpfpm:7.2-rev0
      working_dir: /application
      networks:
        - proxy
      dns: 172.20.10.250
      volumes:
        - ../..:/application/www:cached
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
        - ./wp-cli.yml:/application/wp-cli.yml
        - ./composer-config.json:/root/.composer/auth.json
        - ./composer-cache:/application/composer-cache
      links:
        - memcached
      external_links:
        - "tribe-mysql:mysql"
        - "tribe-mail:mail"
      environment:
        - COMPOSER_MEMORY_LIMIT=-1
        - COMPOSER_ALLOW_SUPERUSER=1
        - COMPOSER_CACHE_DIR=/application/composer-cache
        - PAGER=more

    webserver:
      image: nginx:stable-alpine
      working_dir: /application
      environment:
        - VIRTUAL_HOST=wcorl.tribe,*.wcorl.tribe
      volumes:
        - ../..:/application/www:cached
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./phpdocker/nginx/fastcgi.conf:/etc/nginx/fastcgi_params
      networks:
        - proxy
      links:
        - php-fpm

networks:
  proxy:
    external:
      name: global_proxy


